export const SITE_CONFIG = {
  name: 'THẦY HOTB',
  title: 'Thầy HOTB Learning Hub - Kho kiến thức thực chiến',
  slogan: 'Học thực chiến. Làm được việc.',
  logo: '/images/logo.png',
  favicon: '/favicon.ico',
  description:
    'Kho học liệu miễn phí dành cho sinh viên và người mới bắt đầu về Thiết kế đồ họa, UI/UX, Lập trình Web, Frontend, Backend, AI ứng dụng, Marketing và Kỹ năng nghề nghiệp.',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api',
  instructor: {
    name: 'Thầy HOTB',
    title: 'Giảng viên Thiết kế đồ họa & Công nghệ thông tin',
    bio: 'Hơn 10 năm kinh nghiệm giảng dạy và thực chiến tại các trường cao đẳng, đại học. Chuyên gia đào tạo theo định hướng: Học → Làm → Tạo sản phẩm thực tế.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    cover: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    philosophy: 'Kiến thức không có giá trị nếu không được đưa vào thực hành. Tôi tin rằng mọi sinh viên đều có thể thành thạo nghề nếu được học bằng dự án thực chiến và người dẫn dắt tận tâm.',
    stats: [
      { label: 'Năm giảng dạy', value: '10+' },
      { label: 'Học viên đã hướng dẫn', value: '5,000+' },
      { label: 'Video bài giảng', value: '200+' },
      { label: 'Dự án thực tế', value: '100+' },
    ],
  },
  socialLinks: {
    youtube: 'https://www.youtube.com/@thayhotb',
    facebook: 'https://www.facebook.com/thayhotb',
    linkedin: 'https://www.linkedin.com/in/thayhotb',
    github: 'https://github.com/thayhotb',
    email: 'hotb@fpoly.edu.vn',
    phone: '0988 123 456',
    address: 'Cao đẳng FPT Polytechnic',
  },
  navLinks: [
    { label: 'Trang chủ', href: '/' },
    { label: 'Khóa học', href: '/khoa-hoc' },
    { label: 'Bài viết', href: '/bai-viet' },
    { label: 'Chủ đề', href: '/#chu-de' },
    { label: 'Lộ trình', href: '/lo-trinh' },
    { label: 'Giới thiệu', href: '/gioi-thieu' },
    { label: 'Liên hệ', href: '/lien-he' },
  ],
  footerCategories: [
    { label: 'Thiết kế đồ họa', href: '/chu-de/thiet-ke-do-hoa' },
    { label: 'UI/UX Design', href: '/chu-de/ui-ux-design' },
    { label: 'Lập trình Web', href: '/chu-de/lap-trinh-web' },
    { label: 'Frontend Development', href: '/chu-de/frontend-development' },
    { label: 'Backend Development', href: '/chu-de/backend-development' },
    { label: 'AI ứng dụng', href: '/chu-de/ai-ung-dung' },
    { label: 'Digital Marketing', href: '/chu-de/digital-marketing' },
  ],
};
